USE [Sweedish]  
GO  
  
CREATE TABLE [dbo].[snille_ersattningstabell](
	[ersattningsID]  int(10)  NOT NULL AUTO_INCREMENT,
   [ersattningsTyp]  tinyint(4) unsigned DEFAULT '0' COMMENT 'Ett värde för varje typ: Utlägg, traktamente och milersättning. ',
   [ersattningsKommentar]  varchar(255) DEFAULT NULL COMMENT 'Utlägg: vad avses, Traktamente: kommentar ',
   ersattningsKommentar2  varchar(255) DEFAULT NULL,
   ersattningsDatum  datetime DEFAULT NULL COMMENT 'Utlägg: datum, Traktamente: från, Milersättning: datum',
   ersattningsDatum2  datetime DEFAULT '2015-01-01 00:00:00',
   ersattningsAntal  double unsigned DEFAULT '0' COMMENT 'Traktamente: antal, Milersättning: sträcka',
   ersattningsKostnadInkl  double unsigned DEFAULT '0' COMMENT 'Utlägg: kostnad inkl, Traktamente: summa, Milersättning: ersättning ',
   ersattningsKostnadExkl  double unsigned DEFAULT '0' COMMENT 'Utlägg: kostnad exkl, Traktamente: summa, Milersättning: ersättning ',
   ersattningsDebiteraVidare  tinyint(4) unsigned DEFAULT '0',
   ersattningsKopplaTillKund  int(10) unsigned DEFAULT '0',
   ersattningsProjektnummer  varchar(50) DEFAULT NULL,
   ersattningsProjektID  bigint(20) unsigned DEFAULT '0',
   ersattningsPaLon  tinyint(3) unsigned DEFAULT '0',
   ersattningsGodkand  tinyint(3) unsigned DEFAULT '0',
   personalID  bigint(20) unsigned DEFAULT '0',
   uppdragsID  bigint(20) unsigned DEFAULT '0',
   ersattningHeldagBelopp  double unsigned DEFAULT '0',
   ersattningHeldagAntal  double unsigned DEFAULT '0',
   ersattningHalvdagBelopp  double unsigned DEFAULT '0',
   ersattningHalvdagAntal  double unsigned DEFAULT '0',
   ersattningNattBelopp  double unsigned DEFAULT '0',
   ersattningNattAntal  double unsigned DEFAULT '0',
   ersattningFruBelopp  double unsigned DEFAULT '0',
   ersattningFruAntal  double unsigned DEFAULT '0',
   ersattningLunchBelopp  double unsigned DEFAULT '0',
   ersattningLunchAntal  double unsigned DEFAULT '0',
   ersattningMiddagBelopp  double unsigned DEFAULT '0',
   ersattningMiddagAntal  double unsigned DEFAULT '0',
   ersattningFruLuMiBelopp  double unsigned DEFAULT '0',
   ersattningFruLuMiAntal  double unsigned DEFAULT '0',
   ersattningsTraktamenteSverige  tinyint(3) unsigned DEFAULT '1',
   ersattningsAdminkommentar  varchar(255) DEFAULT NULL,
   ersattningsGodkandTimestamp  datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  PRIMARY KEY ( ersattningsID ))  